### PR TITLE
Add 'smtp_sender' to list of parameters

### LINKED ISSUE #35: Notifications by email: Need parameter for FROM address different than smtp_user
If using AWS SES to send an email notification, there needs to be a parameter for **FROM** address which differs from _smtp_user_. 

At this time, there isn't any "**FROM**" parameter documented, so I presume that one does not exist: https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-Notification-and-Alerting

### PR DESCRIPTION
**Pull request by jpfreeley**
Add 'smtp_sender' to list of parameters to allow setting "FROM" email address. 

closes https://github.com/carrier-io/carrier-io/issues/35

### CODE REVIEW

**Review by arozumenko — APPROVED** [review]

**Comment by arozumenko** [comment]
@jpfreeley you would want to update README
@hunkom will take care about packaging

**Review by hunkom — COMMENTED** [review]
Hi @jpfreeley,

In order to use this parameter, it should be passed to lambda_function.lambda_handler (like the other parameters for smtp config) and processed in parse_args method.

Also could you please validate this parameter in lambda_handler method in "# Check required params" section.

Thank you!

**Review by arozumenko — CHANGES_REQUESTED** [review]
Please address comments re lambda_handler and parse_args

**Comment by arozumenko** [comment]
One other thing is in here 
https://github.com/carrier-io/performance_email_notification/blob/master/lambda_function.py

**Review by arozumenko — APPROVED** [review]

**Comment by jpfreeley** [comment]
@arozumenko can you update the original wiki page to match the updated README? https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-Notification-and-Alerting

**Comment by arozumenko** [comment]
yes, will do

**Pull request merged**
